[package]
edition      = "2024"
name         = "rgb-blinky-async"
rust-version = "1.88"
version      = "0.1.0"

[[bin]]
name = "rgb-blinky-async"
path = "./src/bin/main.rs"

[dependencies]
esp-hal = { version = "~1.0", features = ["defmt", "esp32c6", "unstable"] }

esp-rtos = { version = "0.2.0", features = ["defmt", "embassy", "esp32c6"] }

defmt                  = "1.0.1"
esp-bootloader-esp-idf = { version = "0.4.0", features = ["defmt", "esp32c6"] }

embassy-executor = { version = "0.9.1", features = ["defmt"] }
embassy-time     = { version = "0.5.0", features = ["defmt"] }
esp-println      = { version = "0.16.1", features = ["defmt-espflash", "esp32c6"] }

critical-section = "1.2.0"
static_cell      = "2.1.1"
esp-hal-smartled = "0.17.0"
esp32c6 = "0.22.0"
smart-leds = "0.4.0"
embassy-sync = "0.7.2"


[profile.dev]
# Rust debug is too slow.
# For debug builds always builds with some optimization
opt-level = "s"

[profile.release]
codegen-units    = 1     # LLVM can perform better optimizations using a single thread
debug            = 2
debug-assertions = false
incremental      = false
lto              = 'fat'
opt-level        = 's'
overflow-checks  = false
